### ISSUE TITLE
please update the api

### ISSUE THREAD

**Issue by msooraj9452** [nepodev/radio-browser#3]
i think Radio Browser updated there apis but Your package is not running on them .
and it is not detecting newly added stations . Please update it will help a lot :)

**Comment by nepodev** [comment]
thanks for the issue. yes, some changes are not implemented. I'll check that.

> ... and it is not detecting newly added stations

at this time the package points to the old api-host. this can be changed by setting the property `service_url`
hosts are described at <https://github.com/segler-alex/radiobrowser-api-rust/blob/master/README.md>

**Comment by nepodev** [comment]
made update to use the new api-hosts by default. add some new methods.
