### ISSUE TITLE
some error with new update

### ISSUE THREAD

**Issue by actuallyabhi** [nepodev/radio-browser#4]
[copied from console ] 
POST https://0.0.0.0/json/stations/bytag/hindi net::ERR_CONNECTION_REFUSED
TypeError: Failed to fetch

**Comment by nepodev** [comment]
there is an wrong IP (0.0.0.0). Please post your code example.

i. e. this works for me
```
const radioBrowser = require('radio-browser')
const start = async () => {
  let data = await radioBrowser.getStations({by: 'tag', searchterm: 'hindi'})
  console.log(data)
}
start()
```
<https://repl.it/repls/WoodenAromaticReference>

Or set the service_url before first request. 
i.e. `radioBrowser.service_url = 'https://de1.api.radio-browser.info/'`

**Comment by nepodev** [comment]
When used in a browser, e.g. with reactjs, the `service_url` property must be set manually.
e.g. `radioBrowser.service_url = 'https://de1.api.radio-browser.info/'`
Reason: This module uses node dns to determine a random server. This cannot be used in a browser.
