### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by kaaax0815** [nepodev/radio-browser#7]
Please add Typescript Declarations or move to Typescript

I am currently working on this. I'll make a pr as soon its done

**Comment by nepodev** [comment]
Hi @kaaax0815,

this is a pure nodejs project and I'll keep it that way. Adding ts declarations to this project is the wrong way.
And I will not switch to TS as long as I'm ok with nodejs :slightly_smiling_face:

There is a ts project for radio browser right here https://github.com/ivandotv/radio-browser-api

**Comment by kaaax0815** [comment]
I dont understand this decision. Typescript Support is good so people who use Typescript can also use this Project. Typescript also is NodeJS
